### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by CountMurphy** [MathisP75/daemon-kde-mk2#1]
Hello! At the risk of sounding dumb, how do you install v2? I've "copied" the following instructions from v1:

```
cp -r Kvantum ~/.config/Kvantum/
cp color-schemes/ ~/.local/share/color-schemes/ -r
```

But only Colors is updated in my system settings.  Plasma style, and Window Decorations still only list Daemon v1.

**Comment by MathisP75** [comment]
This version is far from finished, I only just started making the kvantum theme. I will give updates on the progress in the README, where you can find a road map.
