### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by Zoestra** [MathisP75/daemon-kde-mk2#18]
A couple of things i've noticed with the icons i wanted to bring up.

an icon for Obsidian would be greatly appreciated. They've got some resources for customizing their logo [here](https://obsidian.md/blog/new-obsidian-icon/)

a set of plain letters would be appreciated to help cover the gaps, since you obviously cant get everything.

finally, the jetbrains IDE icons arent getting applied on my end. this might be due to how they were installed (via the jetbrains toolbox). idk if this is something you can fix, but i figured i should flag it up.
on the jetbrains front, an icon for Fleet would be appreciated too.

i'll reply with more if i find more apps that need icons.

(btw, someone commented today that this theme doesnt even look like linux anymore, but looks like some kind of future OS. thats winning in my book)

**Comment by MathisP75** [comment]
Thanks for the feedback! I will definitely be making these icons, I'll update you when I do. I am not sure what's the Jetbrains icons are about, is it icons that are inside the app? I plan on making a theme for Jetbrains since you asked, but I didn't start yet, I am working on the VScode theme.

**Comment by MathisP75** [comment]
I have made an icon for Obsidian (not pushed yet) and I will make one for Fleet. However, I am not sure what you mean with the Jetbrains icons. Is it the application icons or icons inside the app itself? And what did you apply with the toolbox? I'll make icons for alphabet letters too.

**Comment by MathisP75** [comment]
I added icons for OBS, Obsidian, Fleet and all the alphabet letters! Feel free to open another issue with more details regarding your problem with Jetbrain icons.
